// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StorageAPI.Models.DbContexts;

#nullable disable

namespace StorageAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230531225508_DataSeed")]
    partial class DataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StorageAPI.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Cost")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Products", "Storages");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Cost = 7.8m,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2L,
                            Cost = 12m,
                            Name = "Banana"
                        },
                        new
                        {
                            Id = 3L,
                            Cost = 8.5m,
                            Name = "Orange"
                        },
                        new
                        {
                            Id = 4L,
                            Cost = 10m,
                            Name = "Brocoli"
                        });
                });

            modelBuilder.Entity("StorageAPI.Models.StateOfStorage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(20,0)");

                    b.Property<long>("StorageId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StorageId");

                    b.ToTable("StatesOfStorages", "Storages");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ProductId = 1L,
                            Quantity = 20m,
                            StorageId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            ProductId = 2L,
                            Quantity = 2m,
                            StorageId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            ProductId = 3L,
                            Quantity = 4m,
                            StorageId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            ProductId = 4L,
                            Quantity = 8m,
                            StorageId = 2L
                        });
                });

            modelBuilder.Entity("StorageAPI.Models.Storage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("KindOfStorage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Storages", "Storages");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "Somewhere in Belgrade",
                            KindOfStorage = "Fruits",
                            Name = "Storage1"
                        },
                        new
                        {
                            Id = 2L,
                            Address = "Somewhere else in Belgrade",
                            KindOfStorage = "Vegetables",
                            Name = "Storage2"
                        });
                });

            modelBuilder.Entity("StorageAPI.Models.StateOfStorage", b =>
                {
                    b.HasOne("StorageAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StorageAPI.Models.Storage", "Storage")
                        .WithMany()
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Storage");
                });
#pragma warning restore 612, 618
        }
    }
}
